namespace qoldau.suap.miniagent.Mitsubishi.Enums {
    public enum ErrorCodesEnum {
        Fine = 0x00, // No Error
        NotExistError = 0x4031, // The scanned device or I/O does not exist. Verify PLC device range configuration or existence of File register.
        WrongConfigError = 0xC050, // Configure the Q71 card for binary and restart the module.
        IncorrectIO1 = 0xC051, // The number of points to read/write is incorrect, contact Adroit technical support.
        IncorrectIO2 = 0xC052,
        IncorrectIO3 = 0xC053,
        IncorrectIO4 = 0xC054,
        IncorrectIO5 = 0xC055,
        DeviceOrIONotExist = 0xC056, // The scanned device or I/O does not exist. The starting address + length of the request exceeds the number of points in the PLC. Verify PLC device range configuration.
        LengMissmatch1 = 0xC057, //  Requested data length miss-match, contact Adroit technical support.
        LengMissmatch2 = 0xC058,
        InvalidCommand = 0xC059, // The command issued is invalid, contact Adroit technical support.
        DeviceNotExist = 0xC05B, // The requested device does not exist. Verify PLC device configuration.
        // 03E8 thru 4FFF	Are generated by the CPU, see CPU error code manual for more detail.
    }
}
